### ISSUE TITLE
pl forward vs step functions

### ISSUE THREAD

**Issue by emrecanacikgoz** [denizyuret/calvin-scripts#2]
regarding to your log [here]( https://github.com/denizyuret/calvin-scripts/blob/b19743b80e93706f87eff1b96f61c10db3e23cc2/ChangeLog#L11) Hocam; you don't have to use both of them for your case, step function is enough to iterate over each batch. 

In pl or pytorch, forward() should define your predictions/inference; it encapsulates the way your model would be used. You can choose to have it in your step() function or not. 

However; if you are using self(x) rather than self.mlp(x) (see [here](https://github.com/emrecanacikgoz/robot-language/blob/e1823d5353161eaf8198443359422cc6e8800d54/blind_robot/models/mlp.py#L81)), you must define a forward() method. self(x) automatically calls the forward() function for you.

**Reference:** You can check also the [link](https://pytorch-lightning.readthedocs.io/en/1.6.0/starter/introduction.html) Hocam, there is a FORWARD vs TRAINING_STEP section provided by pl.

**Comment by denizyuret** [comment]
I added a forward function, because I couldn’t get prediction_step to work
otherwise. I wanted to get model predictions to add the top5 to the
visualization. Let me know if you’d like to use it.

**Comment by emrecanacikgoz** [comment]
Ohh I see thats a good idea, I'll check that.
