### ISSUE TITLE
code confusion in calvindataset2

### ISSUE THREAD

**Issue by emrecanacikgoz** [denizyuret/calvin-scripts#3]
Hi, I am a bit confused about the aim of that [line](https://github.com/denizyuret/calvin-scripts/blob/beca744ac9171f175b37c762365f781f07e7f5b3/model/loaddata.py#L109). As I remember, that line is generated by chatGPT; I was wondering if there is a more simple and readable way; e.g. reshape(-1), flatten, etc. Could you briefly go over that line Hocam?

**Comment by denizyuret** [comment]
ravel and reshape(-1) do roughly the same thing apparently.
https://www.techentice.com/numpy-difference-between-reshape-flatten/

np.ix_ does whatever regular julia indexing would have done, i.e. in Julia
we could have said data[p-window+1:p,features], but stupid Python doesn't
like that and np.ix_ does the right thing.
