### ISSUE TITLE
gripper width - gripper open/close confusion

### ISSUE THREAD

**Issue by emrecanacikgoz** [denizyuret/calvin-scripts#5]
The last index of robot_obs is gripper open or close [-1/1] and 7th index is gripper width in original Calvin, see [here](https://github.com/mees/calvin/tree/main/dataset#state-observation). But it vice-verse for your case in line: https://github.com/denizyuret/calvin-scripts/blob/183fb06cba9466d8bedd72c32994bba4e8b931b9/loaddata.py#L221. Did you change it specifically Hocam or it is a small issue?

I am going to drop gripper-open/close variable in robot_obs while training action-decoder; to make it 96-dimensional and make it divisible by number of heads..

**Comment by denizyuret** [comment]
I think that is the way it is ordered in my file as well: I call the gripper width (continuous one in meters) "tcpg" and the open-close (binary one, +-1) "armg". Is this not true?

**Comment by emrecanacikgoz** [comment]
ohh okay, my bad.. its true, sorry for that..
